const API='https://api.binance.com';
const FAPI='https://fapi.binance.com';
const WS='wss://stream.binance.com:9443/ws';
const FWS='wss://fstream.binance.com/ws';

const state={symbol:'BTCUSDT',interval:'5m',candles:[],book:null,trades:[],liquidations:[],funding:null,oi:null,ws:[],stats:{},nav:'OVERVIEW'};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const fmt=(x,d=2)=>Number.isFinite(x)?x.toLocaleString(undefined,{maximumFractionDigits:d}):'—';
const pct=(x,d=2)=>Number.isFinite(x)?`${x>=0?'+':''}${x.toFixed(d)}%`:'—';
function clamp(x,a,b){return Math.max(a,Math.min(b,x));}
function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}
function std(a){if(a.length<2)return NaN;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
function ema(a,n){if(!a.length)return [];const k=2/(n+1);let e=a[0];const out=[e];for(let i=1;i<a.length;i++){e=a[i]*k+e*(1-k);out.push(e)}return out}
function rsi(a,n=14){if(a.length<n+1)return NaN;let g=0,l=0;for(let i=a.length-n;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}const rs=l?g/l:100;return 100-100/(1+rs)}
function realizedVol(c,n=48){if(c.length<3)return NaN;const rs=[];for(let i=Math.max(1,c.length-n);i<c.length;i++)rs.push(Math.log(c[i].close/c[i-1].close));return std(rs)*Math.sqrt(rs.length)*100}
function zscore(x,a){const m=mean(a),s=std(a);return s?((x-m)/s):0}
function buildFeatures(){const c=state.candles;if(c.length<40)return null;const closes=c.map(x=>x.close), vols=c.map(x=>x.volume);const rets=closes.slice(1).map((x,i)=>Math.log(x/closes[i]));const e20=ema(closes,20).at(-1),e50=ema(closes,50).at(-1);const rv=realizedVol(c,48);const mom1=closes.at(-1)/closes.at(-13)-1,mom5=closes.at(-1)/closes.at(-61)-1;const r=rsi(closes,14);const avgVol=mean(vols.slice(-40));const volRatio=vols.at(-1)/avgVol;const fair=mean(closes.slice(-50));const mr=(closes.at(-1)-fair)/(std(closes.slice(-50))||1);const book=state.book||{};const bid=(book.bids||[]).slice(0,20).reduce((s,x)=>s+x[1],0),ask=(book.asks||[]).slice(0,20).reduce((s,x)=>s+x[1],0);const imb=(bid+ask)?(bid-ask)/(bid+ask):0;const micro=(book.bids?.[0]&&book.asks?.[0])?(book.bids[0][0]*book.asks[0][1]+book.asks[0][0]*book.bids[0][1])/((book.bids[0][1]+book.asks[0][1])||1):closes.at(-1);const spread=(book.bids?.[0]&&book.asks?.[0])?(book.asks[0][0]-book.bids[0][0])/micro*10000:NaN;
let trend=closes.at(-1)>e20&&e20>e50?'UPTREND':closes.at(-1)<e20&&e20<e50?'DOWNTREND':'RANGE';let regime=Math.abs(mom5)>0.015&&rv>2.5?'HIGH-VOL TREND':rv>2.5?'VOLATILE':Math.abs(mr)<.65?'MEAN-REVERT':'MIXED';
const alpha={momentum:clamp((mom1*6+mom5*2)*100, -1,1),meanReversion:clamp(-mr*.25,-1,1),microstructure:clamp(imb*1.2,-1,1),trend:trend==='UPTREND'?.55:trend==='DOWNTREND'?-0.55:0};const weights=regime==='MEAN-REVERT'?{momentum:.1,meanReversion:.6,microstructure:.2,trend:.1}:regime.includes('TREND')?{momentum:.35,meanReversion:.1,microstructure:.35,trend:.2}:{momentum:.25,meanReversion:.25,microstructure:.35,trend:.15};const score=Object.keys(alpha).reduce((s,k)=>s+alpha[k]*weights[k],0);const confidence=clamp(50+Math.abs(score)*42+Math.abs(imb)*18,0,99);const direction=score>.12?'LONG':score<-.12?'SHORT':'NEUTRAL';const entry=closes.at(-1);const atr=mean(c.slice(-20).map(x=>x.high-x.low));const sl=direction==='LONG'?entry-1.3*atr:direction==='SHORT'?entry+1.3*atr:entry;const tp=direction==='LONG'?entry+2.1*atr:direction==='SHORT'?entry-2.1*atr:entry;const costBps=Math.max(1.5,spread+2.5);const edgeBps=Math.abs(score)*rv*5;return{price:entry,e20,e50,r,mom1,mom5,rv,volRatio,mr,imb,spread,micro,trend,regime,alpha,score,confidence,direction,atr,sl,tp,costBps,edgeBps,netBps:edgeBps-costBps};}
async function jget(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json();}
async function loadHistory(){const data=await jget(`${API}/api/v3/klines?symbol=${state.symbol}&interval=${state.interval}&limit=1000`);state.candles=data.map(k=>({time:k[0]/1000,open:+k[1],high:+k[2],low:+k[3],close:+k[4],volume:+k[5]}));renderChart();updateAll();}
async function loadDerivs(){try{state.funding=(await jget(`${FAPI}/fapi/v1/premiumIndex?symbol=${state.symbol}`)).lastFundingRate;state.oi=(await jget(`${FAPI}/fapi/v1/openInterest?symbol=${state.symbol}`)).openInterest;updateDerivs()}catch(e){console.warn(e)}}
function connect(){state.ws.forEach(x=>{try{x.close()}catch{}});state.ws=[];const s=state.symbol.toLowerCase();
const k=new WebSocket(`${WS}/${s}@kline_${state.interval}`);k.onopen=()=>setLive(true);k.onmessage=e=>{const d=JSON.parse(e.data).k;if(!state.candles.length)return;const x={time:d.t/1000,open:+d.o,high:+d.h,low:+d.l,close:+d.c,volume:+d.v};const last=state.candles.at(-1);if(last.time===x.time)state.candles[state.candles.length-1]=x;else state.candles.push(x);state.candles=state.candles.slice(-1000);renderChart();updateAll()};k.onerror=()=>setLive(false);k.onclose=()=>setTimeout(connect,2500);state.ws.push(k);
const b=new WebSocket(`${WS}/${s}@depth20@100ms`);b.onmessage=e=>{const d=JSON.parse(e.data);state.book={bids:d.bids,asks:d.asks};renderBook();updateAll()};state.ws.push(b);
const t=new WebSocket(`${WS}/${s}@aggTrade`);t.onmessage=e=>{const d=JSON.parse(e.data),q=+d.q;state.trades.unshift({price:+d.p,qty:q,buy:d.m===false,time:d.T});state.trades=state.trades.slice(0,80);renderTrades()};state.ws.push(t);
const l=new WebSocket(`${FWS}/${s}@forceOrder`);l.onmessage=e=>{try{const d=JSON.parse(e.data).o;state.liquidations.unshift({price:+d.ap||+d.p,qty:+d.q,side:d.S,time:d.T});state.liquidations=state.liquidations.slice(0,40);renderLiq()}catch{}};state.ws.push(l);
}
function setLive(v){$('#live').textContent=v?'LIVE':'RECONNECTING';$('#liveDot').style.background=v?'var(--green)':'var(--red)'}
let chart,series;
function renderChart(){if(!window.LightweightCharts)return;const el=$('#chart');if(!chart){chart=LightweightCharts.createChart(el,{layout:{background:{color:'#070a11'},textColor:'#69758a'},grid:{vertLines:{color:'#0f1520'},horzLines:{color:'#0f1520'}},rightPriceScale:{borderColor:'#17202e'},timeScale:{borderColor:'#17202e',timeVisible:true,secondsVisible:false},crosshair:{mode:0}});series=chart.addCandlestickSeries({upColor:'#31d39a',downColor:'#ff647b',borderVisible:false,wickUpColor:'#31d39a',wickDownColor:'#ff647b'});new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el)}series.setData(state.candles);chart.timeScale().fitContent()}
function updateAll(){state.stats=buildFeatures();const f=state.stats;if(!f)return;$('#price').textContent=`$${fmt(f.price,2)}`;$('#rsi').textContent=fmt(f.r,1);$('#rv').textContent=`${fmt(f.rv,2)}%`;$('#imb').textContent=pct(f.imb*100,1);$('#regime').textContent=f.regime;$('#trend').textContent=f.trend;$('#signal').textContent=f.direction;$('#confidence').textContent=`${fmt(f.confidence,0)}%`;$('#score').textContent=f.score.toFixed(3);$('#edge').textContent=`${fmt(f.edgeBps,1)} bps`;$('#cost').textContent=`${fmt(f.costBps,1)} bps`;$('#net').textContent=`${fmt(f.netBps,1)} bps`;$('#sl').textContent=`$${fmt(f.sl,2)}`;$('#tp').textContent=`$${fmt(f.tp,2)}`;$('#entry').textContent=`$${fmt(f.price,2)}`;$('#signal').className=`big ${f.direction==='LONG'?'up':f.direction==='SHORT'?'down':''}`;$('#confidenceBar').style.width=`${f.confidence}%`;renderAlpha(f);updateModePanels(f)}
function renderAlpha(f){const rows=[['Momentum',f.alpha.momentum],['Mean Reversion',f.alpha.meanReversion],['Microstructure',f.alpha.microstructure],['Trend',f.alpha.trend]];$('#alpha').innerHTML=rows.map(r=>`<div class="metricrow"><span>${r[0]}</span><b class="${r[1]>=0?'up':'down'}">${r[1]>=0?'+':''}${r[1].toFixed(3)}</b></div>`).join('')}
function updateDerivs(){$('#funding').textContent=state.funding?`${(+state.funding*100).toFixed(4)}%`:'—';$('#oi').textContent=state.oi?fmt(+state.oi,0):'—'}
function updateModePanels(f){$('#fair').textContent=`$${fmt(mean(state.candles.slice(-50).map(x=>x.close)),2)}`;$('#mrz').textContent=f.mr.toFixed(2);$('#spread').textContent=fmt(f.spread,2);$('#micro').textContent=`$${fmt(f.micro,2)}`;$('#mom1').textContent=pct(f.mom1*100,2);$('#mom5').textContent=pct(f.mom5*100,2);$('#volratio').textContent=`${fmt(f.volRatio,2)}x`}
function renderBook(){if(!state.book)return;const make=(a)=>a.slice(0,8).map(x=>`<div class="bookrow"><span>${fmt(+x[0],2)}</span><b>${fmt(+x[1],4)}</b></div>`).join('');$('.ask').innerHTML=make(state.book.asks.slice().reverse());$('.bid').innerHTML=make(state.book.bids)}
function renderTrades(){if(!state.trades.length)return;$('#trades').innerHTML=state.trades.slice(0,16).map(t=>`<div class="metricrow"><span>${new Date(t.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><b class="${t.buy?'up':'down'}">${fmt(t.price,2)} · ${fmt(t.qty,3)}</b></div>`).join('')}
function renderLiq(){if(!state.liquidations.length)return;$('#liqs').innerHTML=state.liquidations.slice(0,10).map(x=>`<div class="metricrow"><span>${x.side}</span><b class="${x.side==='BUY'?'up':'down'}">${fmt(x.price,2)} · ${fmt(x.qty,3)}</b></div>`).join('')}
function nav(name){state.nav=name;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));$('#viewTitle').textContent=name;$$('[data-view]').forEach(x=>x.classList.toggle('hidden',x.dataset.view!==name&&name!=='OVERVIEW'));}
function bind(){ $$('.nav button').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#symbol').onchange=async e=>{state.symbol=e.target.value;await loadHistory();await loadDerivs();connect()};$('#tf').onchange=async e=>{state.interval=e.target.value;await loadHistory();connect()};$('#toggleSide').onclick=()=>$('#right').classList.toggle('open');$('#closeSide').onclick=()=>$('#right').classList.remove('open');$('#refresh').onclick=()=>location.reload();$('#riskModalBtn').onclick=()=>$('#riskModal').classList.add('open');$('#closeModal').onclick=()=>$('#riskModal').classList.remove('open');}
async function boot(){bind();nav('OVERVIEW');await loadHistory();await loadDerivs();connect();setInterval(loadDerivs,15000);}
window.addEventListener('load',()=>{if(window.LightweightCharts)boot();else setTimeout(boot,500)});
